# Generated by Django 5.2.13 on 2026-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(help_text='The raw complaint text submitted by the student.')),
                ('complaint_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', help_text='Whether the complaint is public (visible to all) or private.', max_length=10)),
                ('category', models.CharField(choices=[('Cleanliness', 'Cleanliness'), ('Mess', 'Mess'), ('Washroom', 'Washroom'), ('Furniture', 'Furniture'), ('Water Cooler', 'Water Cooler'), ('Security', 'Security'), ('Electricity', 'Electricity'), ('WiFi', 'WiFi'), ('Other', 'Other')], default='Other', help_text='The category of the complaint.', max_length=20)),
                ('block', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], help_text='The hostel block (A/B/C/D).', max_length=1)),
                ('floor', models.CharField(choices=[('Ground', 'Ground Floor'), ('First', 'First Floor'), ('Second', 'Second Floor'), ('Third', 'Third Floor')], help_text='The floor where the complaint originates.', max_length=10)),
                ('students_affected', models.PositiveIntegerField(default=1, help_text='Approximate number of students affected.')),
                ('support_count', models.PositiveIntegerField(default=0, help_text='Number of students who supported / upvoted this complaint.')),
                ('predicted_priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='', help_text='Priority predicted by the ML model (set automatically on save).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the complaint was submitted.')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
