# Generated by Django 5.2.13 on 2026-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp when the complaint was submitted.', null=True),
        ),
    ]
