# Generated by Django 5.2.13 on 2026-08-06 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='room_no',
            field=models.CharField(blank=True, default='', help_text='Room number (optional).', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', help_text='Current resolution status, managed by admin.', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The student who submitted this complaint. NULL for CSV-imported rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='block',
            field=models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Cleanliness', 'Cleanliness'), ('Mess', 'Mess'), ('Washroom', 'Washroom'), ('Furniture', 'Furniture'), ('Water Cooler', 'Water Cooler'), ('Security', 'Security'), ('Electricity', 'Electricity'), ('WiFi', 'WiFi'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(help_text='Raw complaint text submitted by the student.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='floor',
            field=models.CharField(choices=[('Ground', 'Ground Floor'), ('First', 'First Floor'), ('Second', 'Second Floor'), ('Third', 'Third Floor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='predicted_priority',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='', help_text='Single source of truth for priority. Updated by ML prediction AND support escalation rules.', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='students_affected',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='support_count',
            field=models.PositiveIntegerField(default=0, help_text='Incremented each time a student clicks Support.'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(help_text='Unique college roll number.', max_length=20, unique=True)),
                ('block', models.CharField(blank=True, default='', help_text='Hostel block (A/B/C/D). Filled after first login.', max_length=1)),
                ('floor', models.CharField(blank=True, default='', max_length=10)),
                ('room_no', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional phone number.', max_length=15)),
                ('profile_complete', models.BooleanField(default=False, help_text='False until the student completes block/floor/room details.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='ComplaintVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='complaints.complaint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Support',
                'verbose_name_plural': 'Complaint Supports',
                'unique_together': {('complaint', 'student')},
            },
        ),
    ]
