# Generated by Django 5.2.13 on 2026-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_add_status_roomno_submittedby_vote_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 hour', '1 hour'), ('2 hours', '2 hours'), ('3 hours', '3 hours'), ('4 hours', '4 hours'), ('5 hours', '5 hours'), ('6 hours', '6 hours'), ('8 hours', '8 hours'), ('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('4 days', '4 days'), ('6 days', '6 days'), ('8 days', '8 days'), ('12 days', '12 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('4 weeks', '4 weeks')], help_text='How long the issue has persisted. NULL for legacy complaints.', max_length=30, null=True),
        ),
    ]
